// SPDX-FileCopyrightText: 2026 the OpenDogShow contributors
// SPDX-License-Identifier: AGPL-3.0-only

import {
    AggregateRoot,
    asAggregateId,
    ClubEventScope,
    DomainError,
    type ClubId,
    type PrincipalId,
} from '../../../../Shared/index.js';
import type { ItemId } from '../../shared/domain-ids.js';
import { ItemCreated } from './events/item-created.js';
import { ItemRenamed } from './events/item-renamed.js';

/**
 * An Item — a club-scoped placeholder aggregate generated by
 * `new:aggregate --scope club` (ADR-0025/0026/0027).
 *
 * Modelled as a class aggregate extending {@link AggregateRoot}: {@link create}
 * takes the owning `clubId` and the acting `createdBy` as typed inputs
 * (ADR-0026) rather than deriving them from a `TransactionScope`, and both
 * {@link create} and {@link rename} record their own fact, scoped to the
 * owning Club (`ClubEventScope`, ADR-0027). A private `#brand` field makes
 * the class **nominal** so a bare `{ id, clubId, … }` object literal is not
 * assignable to `Item` — the type is closed against
 * unvalidated construction. Storage load goes through
 * {@link Item.rehydrate}, which does not record an event.
 */
export class Item extends AggregateRoot {
    // Nominal brand: a bare object literal lacks this private field, so it is
    // not assignable to `Item` — closes the structural-literal leak.
    // eslint-disable-next-line no-unused-private-class-members -- intentional nominal brand; exists for compile-time type pinning, not runtime use.
    readonly #brand = true;
    #name: string;

    readonly id: ItemId;
    readonly clubId: ClubId;
    readonly createdBy: PrincipalId;

    get name(): string {
        return this.#name;
    }

    private constructor(id: ItemId, clubId: ClubId, createdBy: PrincipalId, name: string) {
        super();
        this.id = id;
        this.clubId = clubId;
        this.createdBy = createdBy;
        this.#name = name;
    }

    /** Creates a new Item, recording `ItemCreated` scoped to the owning Club. */
    static create(input: {
        readonly id: ItemId;
        readonly clubId: ClubId;
        readonly createdBy: PrincipalId;
        readonly name: string;
    }): Item {
        assertItemName(input.name);
        const item = new Item(input.id, input.clubId, input.createdBy, input.name);
        item.record(
            ItemCreated.create(asAggregateId(item.id), ClubEventScope.of(item.clubId), {
                name: item.name,
            }),
        );
        return item;
    }

    /**
     * Rehydrates an Item from storage. No event is recorded —
     * rehydration replays past state, it does not produce a new fact.
     */
    static rehydrate(input: {
        readonly id: ItemId;
        readonly clubId: ClubId;
        readonly createdBy: PrincipalId;
        readonly name: string;
    }): Item {
        return new Item(input.id, input.clubId, input.createdBy, input.name);
    }

    /** Renames this Item, recording `ItemRenamed` scoped to the owning Club. */
    rename(name: string): void {
        assertItemName(name);
        this.#name = name;
        this.record(
            ItemRenamed.create(asAggregateId(this.id), ClubEventScope.of(this.clubId), { name }),
        );
    }
}

function assertItemName(name: string): void {
    if (name.trim().length === 0) {
        throw new InvalidItemNameError(name);
    }
}

/** Thrown by {@link Item.create} / {@link Item.rename} for a blank name. */
export class InvalidItemNameError extends DomainError {
    constructor(name: string) {
        super(`Item name must not be blank (got '${name}')`, { name });
    }
}

/**
 * Thrown when a use case looks up an Item by id and none exists
 * — e.g. `RenameItemHandler`, or a hybrid aggregate's create
 * handler deriving its owning `clubId` from this Item.
 */
export class ItemNotFoundError extends DomainError {
    readonly id: ItemId;

    constructor(id: ItemId) {
        super(`No Item found with id '${id}'`, { id });
        this.id = id;
    }
}
