// SPDX-FileCopyrightText: 2026 the OpenDogShow contributors
// SPDX-License-Identifier: AGPL-3.0-only

import {
    AggregateRoot,
    asAggregateId,
    ClubEventScope,
    DomainError,
    type ClubId,
    type PrincipalId,
} from '../../../../Shared/index.js';
import type { TicketId, ItemId } from '../../shared/domain-ids.js';
import { TicketCreated } from './events/ticket-created.js';
import { TicketRenamed } from './events/ticket-renamed.js';

/**
 * A Ticket — a hybrid placeholder aggregate generated by
 * `new:aggregate --scope hybrid --parent item` (ADR-0025/0026/0027).
 *
 * Modelled as a class aggregate extending {@link AggregateRoot}: {@link create}
 * takes the owning `clubId` and the acting `createdBy` as typed inputs
 * (ADR-0026) rather than deriving them from a `TransactionScope` — a
 * Ticket is a **hybrid** aggregate: the owning Club comes from
 * the Item it references (`itemId`), not
 * from who is acting, so an actor with no Club of their own can still create
 * a Ticket owned by the referenced Item's Club.
 * Both {@link create} and {@link rename} record their own fact, scoped to the
 * owning Club (a hybrid aggregate's events are always `club(clubId)` —
 * ADR-0027). A private `#brand` field makes the class **nominal** so a bare
 * `{ id, clubId, … }` object literal is not assignable to
 * `Ticket` — the type is closed against unvalidated
 * construction. Storage load goes through {@link Ticket.rehydrate},
 * which does not record an event.
 */
export class Ticket extends AggregateRoot {
    // Nominal brand: a bare object literal lacks this private field, so it is
    // not assignable to `Ticket` — closes the structural-literal leak.
    // eslint-disable-next-line no-unused-private-class-members -- intentional nominal brand; exists for compile-time type pinning, not runtime use.
    readonly #brand = true;
    #name: string;

    readonly id: TicketId;
    readonly clubId: ClubId;
    readonly createdBy: PrincipalId;
    readonly itemId: ItemId;

    get name(): string {
        return this.#name;
    }

    private constructor(
        id: TicketId,
        clubId: ClubId,
        createdBy: PrincipalId,
        itemId: ItemId,
        name: string,
    ) {
        super();
        this.id = id;
        this.clubId = clubId;
        this.createdBy = createdBy;
        this.itemId = itemId;
        this.#name = name;
    }

    /**
     * Creates a new Ticket, recording `TicketCreated`
     * scoped to the owning Club (`input.clubId`) — a Ticket is
     * Club-owned regardless of which scope the acting principal
     * (`input.createdBy`) created it under (ADR-0026).
     */
    static create(input: {
        readonly id: TicketId;
        readonly clubId: ClubId;
        readonly createdBy: PrincipalId;
        readonly itemId: ItemId;
        readonly name: string;
    }): Ticket {
        assertTicketName(input.name);
        const ticket = new Ticket(
            input.id,
            input.clubId,
            input.createdBy,
            input.itemId,
            input.name,
        );
        ticket.record(
            TicketCreated.create(asAggregateId(ticket.id), ClubEventScope.of(ticket.clubId), {
                name: ticket.name,
            }),
        );
        return ticket;
    }

    /**
     * Rehydrates a Ticket from storage. The owning `clubId` and
     * acting `createdBy` are supplied directly (a stored row carries them as
     * columns). No event is recorded — rehydration replays past state, it
     * does not produce a new fact.
     */
    static rehydrate(input: {
        readonly id: TicketId;
        readonly clubId: ClubId;
        readonly createdBy: PrincipalId;
        readonly itemId: ItemId;
        readonly name: string;
    }): Ticket {
        return new Ticket(input.id, input.clubId, input.createdBy, input.itemId, input.name);
    }

    /** Renames this Ticket, recording `TicketRenamed` scoped to the owning Club. */
    rename(name: string): void {
        assertTicketName(name);
        this.#name = name;
        this.record(
            TicketRenamed.create(asAggregateId(this.id), ClubEventScope.of(this.clubId), { name }),
        );
    }
}

function assertTicketName(name: string): void {
    if (name.trim().length === 0) {
        throw new InvalidTicketNameError(name);
    }
}

/** Thrown by {@link Ticket.create} / {@link Ticket.rename} for a blank name. */
export class InvalidTicketNameError extends DomainError {
    constructor(name: string) {
        super(`Ticket name must not be blank (got '${name}')`, { name });
    }
}

/** Thrown when a use case looks up a Ticket by id and none exists — e.g. `RenameTicketHandler`. */
export class TicketNotFoundError extends DomainError {
    readonly id: TicketId;

    constructor(id: TicketId) {
        super(`No Ticket found with id '${id}'`, { id });
        this.id = id;
    }
}
